/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.30
 * Generated at: 2015-06-02 06:24:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import com.yxq.valuebean.GoodsSingle;

public final class shopCar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      com.yxq.toolbean.shopCar myCar = null;
      synchronized (session) {
        myCar = (com.yxq.toolbean.shopCar) _jspx_page_context.getAttribute("myCar", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (myCar == null){
          myCar = new com.yxq.toolbean.shopCar();
          _jspx_page_context.setAttribute("myCar", myCar, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write('\r');
      out.write('\n');

	ArrayList buylist = myCar.getBuylist();
	float total = 0;
 
      out.write("\r\n");
      out.write("<table border = \"1\" width= \"450\" rules = \"none\" cellspacing = \"0\" cellpadding = \"0\">\r\n");
      out.write("\t<tr height = \"50\">\r\n");
      out.write("\t\t<td colspan = \"5\" align = \"center\">购买的商品如下</td>\r\n");
      out.write("\t</tr> \r\n");
      out.write("\t<tr align = \"center\" height = \"30\" bgcolor = \"lightgrey\">\r\n");
      out.write("\t\t<td width = \"25\">名称</td>\r\n");
      out.write("\t\t<td>价格(元/斤)</td>\r\n");
      out.write("\t\t<td>数量</td>\r\n");
      out.write("\t\t<td>总价(元)</td>\r\n");
      out.write("\t\t<td>移除</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t\r\n");
      out.write("\t");
 if(buylist == null || buylist.size()==0){
      out.write("\r\n");
      out.write("\t<tr height = \"100\">\r\n");
      out.write("\t\t<td colspan = \"5\" align = \"center\">你的购物车为空</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t\r\n");
      out.write("\t");

		}
		else {
			for(int i=0;i<buylist.size();i++){
				GoodsSingle single = (GoodsSingle)buylist.get(i);
				String name = single.getName();
				float price = single.getPrice();
				int num = single.getNum();
				//计算当前商品的价格，并进行四则五入计算
				float money = ((int)((price*num+0.05f)*10))/10f;
				total += money;
	
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<tr align = \"center\" height = \"50\">\r\n");
      out.write("\t\t<td>");
      out.print(name );
      out.write("</td>\r\n");
      out.write("\t\t<td>");
      out.print(price );
      out.write("</td>\r\n");
      out.write("\t\t<td>");
      out.print(num );
      out.write("</td>\r\n");
      out.write("\t\t<td>");
      out.print(money );
      out.write("</td>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<a href = \"docar.jsp?  &action=remove&name=");
      out.print(single.getName());
      out.write("\" >移除</a>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t");

			}
		}
	 
      out.write("\r\n");
      out.write("\t <tr height=\"50\" align = \"center\">\r\n");
      out.write("\t \t<td colspan = \"5\" > 应付金额 ");
      out.print(total );
      out.write("</td>\r\n");
      out.write("\t </tr>\r\n");
      out.write("\t \r\n");
      out.write("\t <tr height = \"50\" align = center>\r\n");
      out.write("\t \t<td colspan = \"2\"><a href = \"show.jsp\">继续购物</a></td>\r\n");
      out.write("\t \t<td colspan = \"3\"><a href = \"docar.jsp? &action=clear\">清空购物车</a></td>\r\n");
      out.write("\t </tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
