/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.30
 * Generated at: 2015-04-29 11:16:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.text.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {


	int num = 0;
	synchronized void add(){
		num++;
	}
 
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 获取时间的函数 -->\r\n");

	Date nowday = new Date();   //实例化对象，获取当前时间
	int hour = nowday.getHours();	//获取日期中的小时
    SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");//定义日期格式化对象
	String time = format.format(nowday);//将指定日期格式化""

      out.write("\r\n");
      out.write("<!-- 获取累计次数的函数 -->\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("<!-- add() -->\r\n");

	add();

      out.write("\r\n");
      out.write(" \r\n");
      out.write(" <html>\r\n");
      out.write(" \t<head>\r\n");
      out.write(" \t\t<title>\r\n");
      out.write(" \t\t\t第一个JSP应用\r\n");
      out.write(" \t\t</title>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<center>\r\n");
      out.write("\t\t\t<table border = \"1\" width = \"300\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<tr height = \"30\">\r\n");
      out.write("\t\t\t\t\t<td align = \"center\">\r\n");
      out.write("\t\t\t\t\t\t温馨提示!\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr height = \"80\">\r\n");
      out.write("\t\t\t\t\t<td align = \"center\">\r\n");
      out.write("\t\t\t\t\t\t现在的时间为:");
      out.print(time );
      out.write("\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr height = \"80\">\r\n");
      out.write("\t\t\t\t\t<td align = \"center\">\r\n");
      out.write("\t\t\t\t\t<!--以下为嵌入到HTML中的java代码，用来生产动态的内容-->    \r\n");
      out.write("\t\t\t\t\t\t");

							if(hour>=24 && hour < 5)
								out.print("现在是凌晨！，时间还早，再睡会吧！");
							else if(hour>5 &&hour<=10)
								out.print("早上好!");
							else if(hour>10 && hour <13)
								out.print("午休时间！");
							else if(hour>=13 && hour <18)
								out.print("下午努力工作吧");
							else if(hour >=18 && hour <21)
								out.print("晚上好");
							else if(hour >=21 && hour <24)
								out.print("注意休息，晚安!");
					 	
      out.write("\r\n");
      out.write("\t\t\t\t \t</td>\r\n");
      out.write("\t\t\t\t </tr>\r\n");
      out.write("\t\t\t</table> \r\n");
      out.write("\t\t</center>\r\n");
      out.write("\t\t\t\t <tr height = \"20\">\r\n");
      out.write("\t\t\t\t \t<td align = \"center\">\r\n");
      out.write("\t\t\t\t \t\t 您是第");
      out.print(num );
      out.write("位访问的游客！\r\n");
      out.write("\t\t\t\t \t</td>\r\n");
      out.write("\t\t\t\t </tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</body>\r\n");
      out.write("\t</title>\r\n");
      out.write("</html>\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
