/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.30
 * Generated at: 2015-06-12 12:49:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import cn.mldn.lxh.dao.impl.*;
import cn.mldn.lxh.vo.*;
import cn.mldn.lxh.dao.*;
import java.util.*;
import java.text.*;

public final class emp_005finsert_005fdo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=GBK");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <title>emp_list.jsp</title>\r\n");
      out.write("    ");

   request.setCharacterEncoding("GBK");
   
   String empno = request.getParameter("empno");
   if(empno == null) empno = "";
   out.println(empno);
   
   String ename = request.getParameter("ename");
   if(ename == null) ename = "";
   out.println(ename);
   
   String job = request.getParameter("job");
   if(job == null) job = "";
   out.println(job);
   
   float sal = Float.parseFloat(request.getParameter("sal"));
   out.println(sal);
   
   SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");//小写的mm表示的是分钟    
   java.util.Date date=sdf.parse(request.getParameter("date")); 
   out.println(date);  
   
    
      out.write("\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("  <body>\r\n");
      out.write("  <h1>添加管理</h1>\r\n");
      out.write(" \r\n");
      out.write("  ");

  try{
       Emp emp = new Emp(empno,ename,job,date,sal);
       IEmpDAO  EDAO= new EmpDAOImpl();
       boolean a = EDAO.doCreate(emp);
       
       if(a == true )
       		
      out.write("添加成功！");
 
       else 
      out.write("添加失败");
 
       
  
      out.write("\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("  ");

  }catch(Exception e){
  
  e.printStackTrace();
  }
   
      out.write("\r\n");
      out.write("   <a href=\"index.jsp?\">返回主页</a>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
