/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.30
 * Generated at: 2015-06-12 13:02:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import cn.mldn.lxh.dao.impl.*;
import cn.mldn.lxh.vo.*;
import cn.mldn.lxh.dao.*;
import java.util.*;
import java.text.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=GBK");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <title>emp_list.jsp</title>\r\n");
      out.write("    ");
request.setCharacterEncoding("GBK"); 
      out.write(" \r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("  <body>\r\n");
      out.write("  <center> <h1>员工管理</h1>\r\n");
      out.write("  <form action=\"index.jsp\" method=\"post\">\r\n");
      out.write("  请输入查询关键字<input type=\"text\" name=\"kw\">\r\n");
      out.write("  <input type=\"submit\" value=\"查询\">\r\n");
      out.write("  </form>\r\n");
      out.write(" \r\n");
      out.write("  ");

  try{
     String keyWord=request.getParameter("kw");
     if(keyWord==null){
         keyWord="";
      }
       IEmpDAO  EDAO= new EmpDAOImpl();
      List<Emp> all=EDAO.findAll(keyWord);
      Iterator<Emp> iter=all.iterator();
     
      out.write("\r\n");
      out.write("  <table border=\"1\" width=\"80%\">\r\n");
      out.write("  <tr>\r\n");
      out.write("  <td>雇员编号</td>\r\n");
      out.write("  <td>雇员姓名</td>\r\n");
      out.write("  <td>雇员工作</td>\r\n");
      out.write("  <td>雇员工资</td>\r\n");
      out.write("  <td>雇员日期</td>\r\n");
      out.write("  <td colspan=\"6\">操 作</td>\r\n");
      out.write("  </tr>\r\n");
      out.write(" \r\n");
      out.write("  ");

  while(iter.hasNext()){
      Emp emp=iter.next();
   
      out.write("\r\n");
      out.write("   <tr>\r\n");
      out.write("   <td>");
      out.print(emp.getEmpno() );
      out.write("</td>\r\n");
      out.write("   <td>");
      out.print(emp.getEname() );
      out.write("</td>\r\n");
      out.write("   <td>");
      out.print(emp.getJob() );
      out.write("</td>\r\n");
      out.write("   <td>");
      out.print(emp.getSal() );
      out.write("</td>\r\n");
      out.write("   <td>");
      out.print(emp.getHiredate() );
      out.write("</td>\r\n");
      out.write("   <td><a href=\"emp_update.jsp?empno=");
      out.print(emp.getEmpno());
      out.write("\">修改</a>\r\n");
      out.write("\t\t<a href=\"emp_delete.jsp?empno=");
      out.print(emp.getEmpno());
      out.write("\">删除</a></td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   ");

   }
    
      out.write("\r\n");
      out.write("    <a href=\"emp_insert.jsp\">雇员添加</a>\r\n");
      out.write("   </table>\r\n");
      out.write("  </center>\r\n");
      out.write("  ");

  }catch(Exception e){
  
  e.printStackTrace();
  }
   
      out.write("\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
