/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.30
 * Generated at: 2015-05-29 08:36:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class doLogon_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t \t<h2>用户登入</h2>\r\n");
      out.write("\t \t<!--\r\n");
      out.write(" \t\t");

			String name = request.getParameter("userName");
			if(name == "null")
				name = "";
			String password = request.getParameter("userPass");
			if(password == "null")
				password = "";
		
      out.write("\r\n");
      out.write("\t\t-->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
      com.wgh.bean.UserInfo user = null;
      user = (com.wgh.bean.UserInfo) _jspx_page_context.getAttribute("user", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (user == null){
        user = new com.wgh.bean.UserInfo();
        _jspx_page_context.setAttribute("user", user, javax.servlet.jsp.PageContext.PAGE_SCOPE);
        out.write("\r\n");
        out.write("\t\t \t\t\t");
        org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("user"), request);
        out.write("\r\n");
        out.write("\t\t");
      }
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write(" \t\r\n");
      out.write("\t</head>\r\n");
      out.write("\t\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t   <!-- 方式1:通过request获取表单数据 -->\r\n");
      out.write("\t\t   <!--  \r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<b>用户名:</b>\r\n");
      out.write("\t\t\t \t");
      out.print(name );
      out.write("\r\n");
      out.write("\t\t\t \t<b>密码:</b>\r\n");
      out.write("\t\t\t \t");
      out.print(password );
      out.write("\r\n");
      out.write("\t\t \t</div>\r\n");
      out.write("\t\t \t--> \r\n");
      out.write("\t\t \t\r\n");
      out.write("\t\t \t<!-- 方式2:通过值javabean获得表单中的数据 -->\t\t\r\n");
      out.write("\t \t\t<div>\r\n");
      out.write("\t \t\t\t<b>用户名:</b>\r\n");
      out.write("\t \t\t\t\t");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.wgh.bean.UserInfo)_jspx_page_context.findAttribute("user")).getName())));
      out.write("\r\n");
      out.write("\t \t\t\t<b>密   码:</b>\r\n");
      out.write("\t \t\t\t\t");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.wgh.bean.UserInfo)_jspx_page_context.findAttribute("user")).getPassword())));
      out.write("\r\n");
      out.write("\t\t\t</div>\t\t \t\t\t\r\n");
      out.write("\t\t \t\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
